steps:
  - id: 'Build image'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-python-app', '.']

  - id: 'Run application'
    name: 'gcr.io/$PROJECT_ID/my-python-app'
    args:
      - '-c'
      - |
        from deploy_module.rules_reader import RulesReader
        rules = RulesReader('rules/dev/datasets').get_all_rules()
        print(rules)

options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

serviceAccount: 'dataplex-vcs@dataplex-dev-437306.iam.gserviceaccount.com'

