steps:
  - id: 'Build image'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-python-app', '.']

  - id: 'Run application'
    name: 'gcr.io/$PROJECT_ID/my-python-app'
    args:
      - '-c'
      - |
        from deploy_module.credentials import CredentialsManager
        manager = CredentialsManager('dev')
        credentials = manager.get_credentials()
        print(credentials)

options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

serviceAccount: 'dataplex-vcs@dataplex-dev-437306.iam.gserviceaccount.com'

