steps:
  - name: 'alpine/git'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        git fetch origin $BRANCH_NAME
        CHANGED_FILES=$(git diff --name-only HEAD HEAD~1)
        echo "Changed files: $CHANGED_FILES"


options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

serviceAccount: 'dataplex-vcs@dataplex-dev-437306.iam.gserviceaccount.com'
