steps:
  - id: 'Install dependencies'
    name: 'python:3.9'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install google-cloud-storage google-oauth2-tool

  - id: 'branch name'
    name: 'python:3.9'
    entrypoint: 'python'
    env:
      - 'BRANCH_NAME=${BRANCH_NAME}'
    args:
      - '-c'
      - |
          import os
          branch_name = os.getenv('BRANCH_NAME')
          print("***********************")
          print(branch_name)
          print("***********************")

  - id: "execution"
    name: 'python:3.9'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        python -c "
        from deploy_module.credentials import CredentialsManager
        manager = CredentialsManager('dev')
        credentials = manager.get_credentials()
        print(credentials)
        "
options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

# Use your service account here
serviceAccount: 'dataplex-vcs@dataplex-dev-437306.iam.gserviceaccount.com'
