steps:
  - id: 'Build image'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-python-app', '.']


  - id: 'Validation'
    name: 'gcr.io/$PROJECT_ID/my-python-app'
    env:
      - 'BRANCH_NAME=$BRANCH_NAME'
      - 'BASE_BRANCH=$_BASE_BRANCH'
      - 'PR=$_PR_NUMBER'
    args:
      - '-c'
      - |
        from deploy_module.git_changes import changed_files
        from deploy_module.deploy import DataScanManager
        import os
        print("*********************************************")
        print(f"Getting GIT changes")
        print("*********************************************")
        
        changed_files = get_changed_files()
        print(changed_files)
        
        branch_name = os.getenv('BRANCH_NAME')
        base_branch = os.getenv('BASE_BRANCH')
        pr = os.getenv('PR')
        print("*********************************************")
        print(f"Validation of PR #{pr}: {branch_name} TO {base_branch}")
        print("*********************************************")

#        manager = DataScanManager(env=base_branch)
#        manager.create_data_scans(validate=True)



options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

serviceAccount: 'dataplex-vcs@dataplex-dev-437306.iam.gserviceaccount.com'
