project_id: dataplex-dev-437306
parent: projects/dataplex-dev-437306/locations/us-central1
results_table: //bigquery.googleapis.com/projects/dataplex-dev-437306/datasets/dataplex_results/tables/results



